export const gradientColors = {
  blue: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#D3F4FA", alpha: 1, position: 0.2 },
    { color: "#2857FF", alpha: 1, position: 0.3 },
    { color: "#A1BAEC", alpha: 1, position: 0.7 },
    { color: "#4056CE", alpha: 1, position: 0.8 },
    { color: "#353B73", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  cyan: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#E0F1FE", alpha: 1, position: 0.2 },
    { color: "#1AC6F6", alpha: 1, position: 0.3 },
    { color: "#74D9EC", alpha: 1, position: 0.7 },
    { color: "#1783A3", alpha: 1, position: 0.8 },
    { color: "#1D495C", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  green: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#9EF0DE", alpha: 1, position: 0.2 },
    { color: "#49F28D", alpha: 1, position: 0.3 },
    { color: "#2DD28D", alpha: 1, position: 0.7 },
    { color: "#047851", alpha: 1, position: 0.8 },
    { color: "#064E37", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  black: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#EEDBF9", alpha: 1, position: 0.2 },
    { color: "#EC5CDB", alpha: 1, position: 0.3 },
    { color: "#F0B2EA", alpha: 1, position: 0.7 },
    { color: "#973086", alpha: 1, position: 0.8 },
    { color: "#642656", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  magenta: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#EEDBF9", alpha: 1, position: 0.2 },
    { color: "#EC5CDB", alpha: 1, position: 0.3 },
    { color: "#F0B2EA", alpha: 1, position: 0.7 },
    { color: "#973086", alpha: 1, position: 0.8 },
    { color: "#642656", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  neutral: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#E5E5E5", alpha: 1, position: 0.2 },
    { color: "#949494", alpha: 1, position: 0.3 },
    { color: "#DCDCDC", alpha: 1, position: 0.7 },
    { color: "#525252", alpha: 1, position: 0.8 },
    { color: "#292929", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  orange: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#FAF9C7", alpha: 1, position: 0.2 },
    { color: "#FF6E1D", alpha: 1, position: 0.3 },
    { color: "#F9B778", alpha: 1, position: 0.7 },
    { color: "#BD3F11", alpha: 1, position: 0.8 },
    { color: "#792C15", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  purple: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#FBE4FB", alpha: 1, position: 0.2 },
    { color: "#B951FB", alpha: 1, position: 0.3 },
    { color: "#E1BEF4", alpha: 1, position: 0.7 },
    { color: "#9139B7", alpha: 1, position: 0.8 },
    { color: "#632A79", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  red: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#FCD5AC", alpha: 1, position: 0.2 },
    { color: "#FE451D", alpha: 1, position: 0.3 },
    { color: "#FAABA7", alpha: 1, position: 0.7 },
    { color: "#B52720", alpha: 1, position: 0.8 },
    { color: "#7D231F", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  teal: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#ADEAF4", alpha: 1, position: 0.2 },
    { color: "#50F8D4", alpha: 1, position: 0.3 },
    { color: "#66E1CC", alpha: 1, position: 0.7 },
    { color: "#168D81", alpha: 1, position: 0.8 },
    { color: "#174A46", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  yellow: [
    { color: "#FFFFFF", alpha: 1, position: 0 },
    { color: "#F58633", alpha: 1, position: 0.2 },
    { color: "#F5F15C", alpha: 1, position: 0.3 },
    { color: "#EFDE44", alpha: 1, position: 0.7 },
    { color: "#DAB718", alpha: 1, position: 0.8 },
    { color: "#966812", alpha: 1, position: 0.9 },
    { color: "#FFFFFF", alpha: 1, position: 1.0 },
  ],
  transparent: [
    { color: "#FFFFFF", alpha: 0, position: 0 },
    { color: "#FFFFFF", alpha: 0, position: 0.2 },
    { color: "#FFFFFF", alpha: 0, position: 0.3 },
    { color: "#FFFFFF", alpha: 0, position: 0.7 },
    { color: "#FFFFFF", alpha: 0, position: 0.8 },
    { color: "#FFFFFF", alpha: 0, position: 0.9 },
    { color: "#FFFFFF", alpha: 0, position: 1.0 },
  ],
  neutralLight: [
    { color: "#FFFFFF", alpha: 0.8, position: 0 },
    { color: "#E5E5E5", alpha: 0.8, position: 0.2 },
    { color: "#949494", alpha: 0.8, position: 0.3 },
    { color: "#DCDCDC", alpha: 0.8, position: 0.7 },
    { color: "#525252", alpha: 0.8, position: 0.8 },
    { color: "#292929", alpha: 0.8, position: 0.9 },
    { color: "#FFFFFF", alpha: 0.8, position: 1.0 },
  ],
};

export type WaveformColor = keyof typeof gradientColors;

export type GradientStop = {
  alpha: number;
  color: string;
  position: number;
};
