import * as FernNavigation from "@fern-api/fdr-sdk/navigation";
import { NodeCollector } from "@fern-api/fdr-sdk/navigation";
import { provideRegistryService } from "@fern-ui/ui";
import { getAuthEdgeConfig } from "@fern-ui/ui/auth";
import { NextApiHandler, NextApiRequest, NextApiResponse } from "next";
import urljoin from "url-join";
import { conformTrailingSlash } from "../../../../utils/trailingSlash";
import { getXFernHostNode } from "../../../../utils/xFernHost";

export const config = {
    maxDuration: 300,
};

type RevalidatePathResult = RevalidatePathSuccessResult | RevalidatePathErrorResult;

interface RevalidatePathSuccessResult {
    success: true;
    url: string;
}

function isSuccessResult(result: RevalidatePathResult): result is RevalidatePathSuccessResult {
    return result.success;
}

interface RevalidatePathErrorResult {
    success: false;
    url: string;
    message: string;
}

function isFailureResult(result: RevalidatePathResult): result is RevalidatePathErrorResult {
    return !result.success;
}

type RevalidatedPaths = {
    successfulRevalidations: RevalidatePathSuccessResult[];
    failedRevalidations: RevalidatePathErrorResult[];
};

const handler: NextApiHandler = async (
    req: NextApiRequest,
    res: NextApiResponse<RevalidatedPaths>,
): Promise<unknown> => {
    // when we call res.revalidate() nextjs uses
    // req.headers.host to make the network request
    const xFernHost = getXFernHostNode(req, true);
    req.headers.host = xFernHost;

    try {
        const authConfig = await getAuthEdgeConfig(xFernHost);

        /**
         * If the auth config is basic_token_verification, we don't need to revalidate.
         *
         * This is because basic_token_verification is a special case where all the routes are protected by a fern_token that
         * is generated by the customer, and so all routes use SSR and are not cached.
         */
        if (authConfig?.type === "basic_token_verification") {
            return res.status(200).json({ successfulRevalidations: [], failedRevalidations: [] });
        }

        const docs = await provideRegistryService().docs.v2.read.getDocsForUrl({ url: xFernHost });

        if (!docs.ok) {
            /**
             * If the error is UnauthorizedError, we don't need to revalidate, since all the routes require SSR.
             */
            return res
                .status(docs.error.error === "UnauthorizedError" ? 200 : 404)
                .json({ successfulRevalidations: [], failedRevalidations: [] });
        }

        const node = FernNavigation.utils.convertLoadDocsForUrlResponse(docs.body);
        const slugCollector = NodeCollector.collect(node);
        const urls = slugCollector.getPageSlugs().map((slug) => conformTrailingSlash(urljoin(xFernHost, slug)));

        const results: RevalidatePathResult[] = [];

        const batchSize = 100; // reduce concurrency per domain
        for (let i = 0; i < urls.length; i += batchSize) {
            const batch = urls.slice(i, i + batchSize);
            results.push(
                ...(await Promise.all(
                    batch.map(async (url): Promise<RevalidatePathResult> => {
                        // eslint-disable-next-line no-console
                        console.log(`Revalidating ${url}`);
                        try {
                            await res.revalidate(`/static/${encodeURI(url)}`);
                            return { success: true, url };
                        } catch (e) {
                            // eslint-disable-next-line no-console
                            console.error(e);
                            return { success: false, url, message: e instanceof Error ? e.message : "Unknown error." };
                        }
                    }),
                )),
            );
        }

        const successfulRevalidations = results.filter(isSuccessResult);
        const failedRevalidations = results.filter(isFailureResult);

        return res
            .status(failedRevalidations.length === 0 ? 200 : successfulRevalidations.length === 0 ? 500 : 207)
            .json({ successfulRevalidations, failedRevalidations });
    } catch (err) {
        // eslint-disable-next-line no-console
        console.error(err);
        return res.status(500).json({ successfulRevalidations: [], failedRevalidations: [] });
    }
};

export default handler;
