changesetBaseRefs:
  - main
  - origin/main

nodeLinker: pnp

npmScopes:
  fern-fern:
    npmRegistryServer: "https://npm.buildwithfern.com/"
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: D7102FD6-02A5-4221-A23B-20231EA5288D
    npmRegistryServer: "https://npm.fontawesome.com/"

packageExtensions:
  "@blueprintjs/eslint-plugin@*":
    dependencies:
      tslib: "*"
  chalk@*:
    dependencies:
      "#supports-color": "npm:supports-color@9.2.2"
  debug@*:
    dependencies:
      supports-color: ^8.1.1
  follow-redirects@*:
    dependencies:
      debug: "*"
  postcss-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
