changesetBaseRefs:
  - main
  - origin/main

nodeLinker: pnp

npmScopes:
  fern-api:
    npmAuthToken: "${YARN_NPM_AUTH_TOKEN}"
  fern-fern:
    npmRegistryServer: "https://npm.buildwithfern.com/"
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "D7102FD6-02A5-4221-A23B-20231EA5288D"

packageExtensions:
  "@blueprintjs/eslint-plugin@*":
    dependencies:
      tslib: "*"
  "@blueprintjs/stylelint-plugin@*":
    dependencies:
      tslib: "*"
  chalk@*:
    dependencies:
      "#supports-color": "npm:supports-color@9.2.2"
  debug@*:
    dependencies:
      supports-color: ^8.1.1
  docsify-cli@*:
    dependencies:
      ansi-colors: "*"
      y18n: "*"
  docsify-server-renderer@*:
    dependencies:
      marked: "*"
      prismjs: "*"
      strip-indent: 3.0.0
  follow-redirects@*:
    dependencies:
      debug: "*"
  inquirer-file-tree-selection-prompt@*:
    dependencies:
      inquirer: ^8.0.0
  postcss-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
