packages:
  - "servers/**"
  - "clis/**"
  - "packages/**"
  - "!packages/**/lib"
  - "!packages/**/dist"
  - "!packages/**/generated"
  - "!servers/**/lib"
  - "!servers/**/dist"
  - "!servers/**/generated"
  - "!**/__test__/**"
