/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ApiApiIdLazyImport = createFileRoute('/api/$apiId')()
const SdkSdkIdIndexLazyImport = createFileRoute('/sdk/$sdkId/')()
const SdkSdkIdJobJobIdLazyImport = createFileRoute('/sdk/$sdkId/job/$jobId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ApiApiIdLazyRoute = ApiApiIdLazyImport.update({
  path: '/api/$apiId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/api.$apiId.lazy').then((d) => d.Route))

const SdkSdkIdIndexLazyRoute = SdkSdkIdIndexLazyImport.update({
  path: '/sdk/$sdkId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/sdk/$sdkId/index.lazy').then((d) => d.Route),
)

const SdkSdkIdJobJobIdLazyRoute = SdkSdkIdJobJobIdLazyImport.update({
  path: '/sdk/$sdkId/job/$jobId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/sdk/$sdkId/job.$jobId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/api/$apiId': {
      id: '/api/$apiId'
      path: '/api/$apiId'
      fullPath: '/api/$apiId'
      preLoaderRoute: typeof ApiApiIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/sdk/$sdkId/': {
      id: '/sdk/$sdkId/'
      path: '/sdk/$sdkId'
      fullPath: '/sdk/$sdkId'
      preLoaderRoute: typeof SdkSdkIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sdk/$sdkId/job/$jobId': {
      id: '/sdk/$sdkId/job/$jobId'
      path: '/sdk/$sdkId/job/$jobId'
      fullPath: '/sdk/$sdkId/job/$jobId'
      preLoaderRoute: typeof SdkSdkIdJobJobIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ApiApiIdLazyRoute,
  SdkSdkIdIndexLazyRoute,
  SdkSdkIdJobJobIdLazyRoute,
})

/* prettier-ignore-end */


/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/api/$apiId",
        "/sdk/$sdkId/",
        "/sdk/$sdkId/job/$jobId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/api/$apiId": {
      "filePath": "api.$apiId.lazy.tsx"
    },
    "/sdk/$sdkId/": {
      "filePath": "sdk/$sdkId/index.lazy.tsx"
    },
    "/sdk/$sdkId/job/$jobId": {
      "filePath": "sdk/$sdkId/job.$jobId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */