openapi: ./openapi.json
default-group: sdk
groups:
  sdk:
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.12.8-rc0
        output:
          location: npm
          url: npm.buildwithfern.com
          package-name: "@fern-fern/vercel"
        config:
          skipResponseValidation: true
          namespaceExport: Vercel
