import { NodeId, PageId, RoleId, Slug } from "@fern-api/fdr-sdk/navigation";

import { withPrunedNavigation } from "./withPrunedNavigation";

describe("withPrunedNavigation", () => {
  it("child should be hidden if parent is hidden", () => {
    expect(
      withPrunedNavigation(
        {
          type: "root",
          child: {
            id: NodeId("1"),
            landingPage: undefined,
            type: "unversioned",
            child: {
              type: "sidebarRoot",
              id: NodeId("2"),
              children: [
                {
                  type: "section",
                  id: NodeId("3"),
                  children: [
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("1"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                  ],
                  title: "Public",
                  slug: Slug("public"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  hidden: true,
                  icon: undefined,
                  viewers: [RoleId("private")],
                  orphaned: undefined,
                  noindex: false,
                  collapsed: false,
                  overviewPageId: PageId("1.mdx"),
                  pointsTo: undefined,
                  featureFlags: [],
                },
              ],
            },
          },
          version: "v2",
          title: "Root",
          slug: Slug("root"),
          canonicalSlug: undefined,
          authed: undefined,
          icon: undefined,
          hidden: false,
          id: NodeId("4"),
          viewers: undefined,
          orphaned: undefined,
          pointsTo: undefined,
          roles: [],
          featureFlags: [],
        },
        {
          visibleNodeIds: [],
          authed: false,
        }
      )
    ).toStrictEqual({
      type: "root",
      child: {
        id: NodeId("1"),
        landingPage: undefined,
        type: "unversioned",
        child: {
          type: "sidebarRoot",
          id: NodeId("2"),
          children: [],
        },
      },
      version: "v2",
      title: "Root",
      slug: Slug("root"),
      canonicalSlug: undefined,
      authed: undefined,
      icon: undefined,
      hidden: false,
      id: NodeId("4"),
      viewers: undefined,
      orphaned: undefined,
      pointsTo: undefined,
      roles: [],
      featureFlags: [],
    });
  });

  it("hidden parent should be visible is child is visible", () => {
    expect(
      withPrunedNavigation(
        {
          type: "root",
          child: {
            id: NodeId("1"),
            landingPage: undefined,
            type: "unversioned",
            child: {
              type: "sidebarRoot",
              id: NodeId("2"),
              children: [
                {
                  type: "section",
                  id: NodeId("3"),
                  children: [
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("5"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                  ],
                  title: "Public",
                  slug: Slug("public"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  hidden: true,
                  icon: undefined,
                  viewers: [RoleId("private")],
                  orphaned: undefined,
                  noindex: false,
                  collapsed: false,
                  overviewPageId: PageId("1.mdx"),
                  pointsTo: undefined,
                  featureFlags: [],
                },
              ],
            },
          },
          version: "v2",
          title: "Root",
          slug: Slug("root"),
          canonicalSlug: undefined,
          authed: undefined,
          icon: undefined,
          hidden: false,
          id: NodeId("4"),
          viewers: undefined,
          orphaned: undefined,
          pointsTo: undefined,
          roles: [],
          featureFlags: [],
        },
        {
          visibleNodeIds: [NodeId("5"), NodeId("3")],
          authed: false,
        }
      )
    ).toStrictEqual({
      type: "root",
      child: {
        id: NodeId("1"),
        landingPage: undefined,
        type: "unversioned",
        child: {
          type: "sidebarRoot",
          id: NodeId("2"),
          children: [
            {
              type: "section",
              id: NodeId("3"),
              children: [
                {
                  type: "page",
                  title: "Should be hidden",
                  slug: Slug("hidden"),
                  pageId: PageId("1.mdx"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  id: NodeId("5"),
                  hidden: undefined,
                  icon: undefined,
                  viewers: [RoleId("everyone")],
                  orphaned: undefined,
                  noindex: false,
                  featureFlags: [],
                },
              ],
              title: "Public",
              slug: Slug("public"),
              canonicalSlug: undefined,
              authed: undefined,
              hidden: true,
              icon: undefined,
              viewers: [RoleId("private")],
              orphaned: undefined,
              noindex: false,
              collapsed: false,
              overviewPageId: PageId("1.mdx"),
              pointsTo: undefined,
              featureFlags: [],
            },
          ],
        },
      },
      version: "v2",
      title: "Root",
      slug: Slug("root"),
      canonicalSlug: undefined,
      authed: undefined,
      icon: undefined,
      hidden: false,
      id: NodeId("4"),
      viewers: undefined,
      orphaned: undefined,
      pointsTo: undefined,
      roles: [],
      featureFlags: [],
    });
  });

  it("deeply hidden child should be hidden if parent is hidden", () => {
    expect(
      withPrunedNavigation(
        {
          type: "root",
          child: {
            id: NodeId("1"),
            landingPage: undefined,
            type: "unversioned",
            child: {
              type: "sidebarRoot",
              id: NodeId("2"),
              children: [
                {
                  type: "section",
                  id: NodeId("3"),
                  children: [
                    {
                      type: "section",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      overviewPageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("5"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                      collapsed: false,
                      pointsTo: undefined,
                      children: [
                        {
                          type: "page",
                          title: "Should be hidden",
                          slug: Slug("hidden"),
                          pageId: PageId("1.mdx"),
                          canonicalSlug: undefined,
                          authed: undefined,
                          id: NodeId("1"),
                          hidden: undefined,
                          icon: undefined,
                          viewers: [RoleId("everyone")],
                          orphaned: undefined,
                          noindex: false,
                          featureFlags: [],
                        },
                      ],
                    },
                  ],
                  title: "Public",
                  slug: Slug("public"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  hidden: true,
                  icon: undefined,
                  viewers: [RoleId("private")],
                  orphaned: undefined,
                  noindex: false,
                  collapsed: false,
                  overviewPageId: PageId("1.mdx"),
                  pointsTo: undefined,
                  featureFlags: [],
                },
              ],
            },
          },
          version: "v2",
          title: "Root",
          slug: Slug("root"),
          canonicalSlug: undefined,
          authed: undefined,
          icon: undefined,
          hidden: false,
          id: NodeId("4"),
          viewers: undefined,
          orphaned: undefined,
          pointsTo: undefined,
          roles: [],
          featureFlags: [],
        },
        {
          visibleNodeIds: [],
          authed: false,
        }
      )
    ).toStrictEqual({
      type: "root",
      child: {
        id: NodeId("1"),
        landingPage: undefined,
        type: "unversioned",
        child: {
          type: "sidebarRoot",
          id: NodeId("2"),
          children: [],
        },
      },
      version: "v2",
      title: "Root",
      slug: Slug("root"),
      canonicalSlug: undefined,
      authed: undefined,
      icon: undefined,
      hidden: false,
      id: NodeId("4"),
      viewers: undefined,
      orphaned: undefined,
      pointsTo: undefined,
      roles: [],
      featureFlags: [],
    });
  });

  it("parent should be visible is deeply hidden child is visible", () => {
    expect(
      withPrunedNavigation(
        {
          type: "root",
          child: {
            id: NodeId("1"),
            landingPage: undefined,
            type: "unversioned",
            child: {
              type: "sidebarRoot",
              id: NodeId("2"),
              children: [
                {
                  type: "section",
                  id: NodeId("3"),
                  children: [
                    {
                      type: "section",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      overviewPageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("5"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                      collapsed: false,
                      pointsTo: undefined,
                      children: [
                        {
                          type: "page",
                          title: "Should be hidden",
                          slug: Slug("hidden"),
                          pageId: PageId("1.mdx"),
                          canonicalSlug: undefined,
                          authed: undefined,
                          id: NodeId("6"),
                          hidden: undefined,
                          icon: undefined,
                          viewers: [RoleId("everyone")],
                          orphaned: undefined,
                          noindex: false,
                          featureFlags: [],
                        },
                      ],
                    },
                  ],
                  title: "Public",
                  slug: Slug("public"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  hidden: true,
                  icon: undefined,
                  viewers: [RoleId("private")],
                  orphaned: undefined,
                  noindex: false,
                  collapsed: false,
                  overviewPageId: PageId("1.mdx"),
                  pointsTo: undefined,
                  featureFlags: [],
                },
              ],
            },
          },
          version: "v2",
          title: "Root",
          slug: Slug("root"),
          canonicalSlug: undefined,
          authed: undefined,
          icon: undefined,
          hidden: false,
          id: NodeId("4"),
          viewers: undefined,
          orphaned: undefined,
          pointsTo: undefined,
          roles: [],
          featureFlags: [],
        },
        {
          visibleNodeIds: [NodeId("6"), NodeId("5"), NodeId("3")],
          authed: false,
        }
      )
    ).toStrictEqual({
      type: "root",
      child: {
        id: NodeId("1"),
        landingPage: undefined,
        type: "unversioned",
        child: {
          type: "sidebarRoot",
          id: NodeId("2"),
          children: [
            {
              type: "section",
              id: NodeId("3"),
              children: [
                {
                  type: "section",
                  title: "Should be hidden",
                  slug: Slug("hidden"),
                  overviewPageId: PageId("1.mdx"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  id: NodeId("5"),
                  hidden: undefined,
                  icon: undefined,
                  viewers: [RoleId("everyone")],
                  orphaned: undefined,
                  noindex: false,
                  featureFlags: [],
                  collapsed: false,
                  pointsTo: undefined,
                  children: [
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("6"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                  ],
                },
              ],
              title: "Public",
              slug: Slug("public"),
              canonicalSlug: undefined,
              authed: undefined,
              hidden: true,
              icon: undefined,
              viewers: [RoleId("private")],
              orphaned: undefined,
              noindex: false,
              collapsed: false,
              overviewPageId: PageId("1.mdx"),
              pointsTo: undefined,
              featureFlags: [],
            },
          ],
        },
      },
      version: "v2",
      title: "Root",
      slug: Slug("root"),
      canonicalSlug: undefined,
      authed: undefined,
      icon: undefined,
      hidden: false,
      id: NodeId("4"),
      viewers: undefined,
      orphaned: undefined,
      pointsTo: undefined,
      roles: [],
      featureFlags: [],
    });
  });

  it("children should be hidden if parent is hidden", () => {
    expect(
      withPrunedNavigation(
        {
          type: "root",
          child: {
            id: NodeId("1"),
            landingPage: undefined,
            type: "unversioned",
            child: {
              type: "sidebarRoot",
              id: NodeId("2"),
              children: [
                {
                  type: "section",
                  id: NodeId("3"),
                  children: [
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("1"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("1"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                  ],
                  title: "Public",
                  slug: Slug("public"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  hidden: true,
                  icon: undefined,
                  viewers: [RoleId("private")],
                  orphaned: undefined,
                  noindex: false,
                  collapsed: false,
                  overviewPageId: PageId("1.mdx"),
                  pointsTo: undefined,
                  featureFlags: [],
                },
              ],
            },
          },
          version: "v2",
          title: "Root",
          slug: Slug("root"),
          canonicalSlug: undefined,
          authed: undefined,
          icon: undefined,
          hidden: false,
          id: NodeId("4"),
          viewers: undefined,
          orphaned: undefined,
          pointsTo: undefined,
          roles: [],
          featureFlags: [],
        },
        {
          visibleNodeIds: [],
          authed: false,
        }
      )
    ).toStrictEqual({
      type: "root",
      child: {
        id: NodeId("1"),
        landingPage: undefined,
        type: "unversioned",
        child: {
          type: "sidebarRoot",
          id: NodeId("2"),
          children: [],
        },
      },
      version: "v2",
      title: "Root",
      slug: Slug("root"),
      canonicalSlug: undefined,
      authed: undefined,
      icon: undefined,
      hidden: false,
      id: NodeId("4"),
      viewers: undefined,
      orphaned: undefined,
      pointsTo: undefined,
      roles: [],
      featureFlags: [],
    });
  });

  it("hidden parent and sibling should be visible is child is visible", () => {
    expect(
      withPrunedNavigation(
        {
          type: "root",
          child: {
            id: NodeId("1"),
            landingPage: undefined,
            type: "unversioned",
            child: {
              type: "sidebarRoot",
              id: NodeId("2"),
              children: [
                {
                  type: "section",
                  id: NodeId("3"),
                  children: [
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("5"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("6"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                  ],
                  title: "Public",
                  slug: Slug("public"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  hidden: true,
                  icon: undefined,
                  viewers: [RoleId("private")],
                  orphaned: undefined,
                  noindex: false,
                  collapsed: false,
                  overviewPageId: PageId("1.mdx"),
                  pointsTo: undefined,
                  featureFlags: [],
                },
              ],
            },
          },
          version: "v2",
          title: "Root",
          slug: Slug("root"),
          canonicalSlug: undefined,
          authed: undefined,
          icon: undefined,
          hidden: false,
          id: NodeId("4"),
          viewers: undefined,
          orphaned: undefined,
          pointsTo: undefined,
          roles: [],
          featureFlags: [],
        },
        {
          visibleNodeIds: [NodeId("5"), NodeId("3")],
          authed: false,
        }
      )
    ).toStrictEqual({
      type: "root",
      child: {
        id: NodeId("1"),
        landingPage: undefined,
        type: "unversioned",
        child: {
          type: "sidebarRoot",
          id: NodeId("2"),
          children: [
            {
              type: "section",
              id: NodeId("3"),
              children: [
                {
                  type: "page",
                  title: "Should be hidden",
                  slug: Slug("hidden"),
                  pageId: PageId("1.mdx"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  id: NodeId("5"),
                  hidden: undefined,
                  icon: undefined,
                  viewers: [RoleId("everyone")],
                  orphaned: undefined,
                  noindex: false,
                  featureFlags: [],
                },
                {
                  type: "page",
                  title: "Should be hidden",
                  slug: Slug("hidden"),
                  pageId: PageId("1.mdx"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  id: NodeId("6"),
                  hidden: undefined,
                  icon: undefined,
                  viewers: [RoleId("everyone")],
                  orphaned: undefined,
                  noindex: false,
                  featureFlags: [],
                },
              ],
              title: "Public",
              slug: Slug("public"),
              canonicalSlug: undefined,
              authed: undefined,
              hidden: true,
              icon: undefined,
              viewers: [RoleId("private")],
              orphaned: undefined,
              noindex: false,
              collapsed: false,
              overviewPageId: PageId("1.mdx"),
              pointsTo: undefined,
              featureFlags: [],
            },
          ],
        },
      },
      version: "v2",
      title: "Root",
      slug: Slug("root"),
      canonicalSlug: undefined,
      authed: undefined,
      icon: undefined,
      hidden: false,
      id: NodeId("4"),
      viewers: undefined,
      orphaned: undefined,
      pointsTo: undefined,
      roles: [],
      featureFlags: [],
    });
  });

  it("deeply hidden children should be hidden if parent is hidden", () => {
    expect(
      withPrunedNavigation(
        {
          type: "root",
          child: {
            id: NodeId("1"),
            landingPage: undefined,
            type: "unversioned",
            child: {
              type: "sidebarRoot",
              id: NodeId("2"),
              children: [
                {
                  type: "section",
                  id: NodeId("3"),
                  children: [
                    {
                      type: "section",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      overviewPageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("5"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                      collapsed: false,
                      pointsTo: undefined,
                      children: [
                        {
                          type: "page",
                          title: "Should be hidden",
                          slug: Slug("hidden"),
                          pageId: PageId("1.mdx"),
                          canonicalSlug: undefined,
                          authed: undefined,
                          id: NodeId("1"),
                          hidden: undefined,
                          icon: undefined,
                          viewers: [RoleId("everyone")],
                          orphaned: undefined,
                          noindex: false,
                          featureFlags: [],
                        },
                        {
                          type: "page",
                          title: "Should be hidden",
                          slug: Slug("hidden"),
                          pageId: PageId("1.mdx"),
                          canonicalSlug: undefined,
                          authed: undefined,
                          id: NodeId("1"),
                          hidden: undefined,
                          icon: undefined,
                          viewers: [RoleId("everyone")],
                          orphaned: undefined,
                          noindex: false,
                          featureFlags: [],
                        },
                      ],
                    },
                  ],
                  title: "Public",
                  slug: Slug("public"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  hidden: true,
                  icon: undefined,
                  viewers: [RoleId("private")],
                  orphaned: undefined,
                  noindex: false,
                  collapsed: false,
                  overviewPageId: PageId("1.mdx"),
                  pointsTo: undefined,
                  featureFlags: [],
                },
              ],
            },
          },
          version: "v2",
          title: "Root",
          slug: Slug("root"),
          canonicalSlug: undefined,
          authed: undefined,
          icon: undefined,
          hidden: false,
          id: NodeId("4"),
          viewers: undefined,
          orphaned: undefined,
          pointsTo: undefined,
          roles: [],
          featureFlags: [],
        },
        {
          visibleNodeIds: [],
          authed: false,
        }
      )
    ).toStrictEqual({
      type: "root",
      child: {
        id: NodeId("1"),
        landingPage: undefined,
        type: "unversioned",
        child: {
          type: "sidebarRoot",
          id: NodeId("2"),
          children: [],
        },
      },
      version: "v2",
      title: "Root",
      slug: Slug("root"),
      canonicalSlug: undefined,
      authed: undefined,
      icon: undefined,
      hidden: false,
      id: NodeId("4"),
      viewers: undefined,
      orphaned: undefined,
      pointsTo: undefined,
      roles: [],
      featureFlags: [],
    });
  });

  it("parent and sibling should be visible is deeply hidden child is visible", () => {
    expect(
      withPrunedNavigation(
        {
          type: "root",
          child: {
            id: NodeId("1"),
            landingPage: undefined,
            type: "unversioned",
            child: {
              type: "sidebarRoot",
              id: NodeId("2"),
              children: [
                {
                  type: "section",
                  id: NodeId("3"),
                  children: [
                    {
                      type: "section",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      overviewPageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("5"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                      collapsed: false,
                      pointsTo: undefined,
                      children: [
                        {
                          type: "page",
                          title: "Should be hidden",
                          slug: Slug("hidden"),
                          pageId: PageId("1.mdx"),
                          canonicalSlug: undefined,
                          authed: undefined,
                          id: NodeId("6"),
                          hidden: undefined,
                          icon: undefined,
                          viewers: [RoleId("everyone")],
                          orphaned: undefined,
                          noindex: false,
                          featureFlags: [],
                        },
                        {
                          type: "page",
                          title: "Should be hidden",
                          slug: Slug("hidden"),
                          pageId: PageId("1.mdx"),
                          canonicalSlug: undefined,
                          authed: undefined,
                          id: NodeId("7"),
                          hidden: undefined,
                          icon: undefined,
                          viewers: [RoleId("everyone")],
                          orphaned: undefined,
                          noindex: false,
                          featureFlags: [],
                        },
                      ],
                    },
                  ],
                  title: "Public",
                  slug: Slug("public"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  hidden: true,
                  icon: undefined,
                  viewers: [RoleId("private")],
                  orphaned: undefined,
                  noindex: false,
                  collapsed: false,
                  overviewPageId: PageId("1.mdx"),
                  pointsTo: undefined,
                  featureFlags: [],
                },
              ],
            },
          },
          version: "v2",
          title: "Root",
          slug: Slug("root"),
          canonicalSlug: undefined,
          authed: undefined,
          icon: undefined,
          hidden: false,
          id: NodeId("4"),
          viewers: undefined,
          orphaned: undefined,
          pointsTo: undefined,
          roles: [],
          featureFlags: [],
        },
        {
          visibleNodeIds: [NodeId("7"), NodeId("5"), NodeId("3")],
          authed: false,
        }
      )
    ).toStrictEqual({
      type: "root",
      child: {
        id: NodeId("1"),
        landingPage: undefined,
        type: "unversioned",
        child: {
          type: "sidebarRoot",
          id: NodeId("2"),
          children: [
            {
              type: "section",
              id: NodeId("3"),
              children: [
                {
                  type: "section",
                  title: "Should be hidden",
                  slug: Slug("hidden"),
                  overviewPageId: PageId("1.mdx"),
                  canonicalSlug: undefined,
                  authed: undefined,
                  id: NodeId("5"),
                  hidden: undefined,
                  icon: undefined,
                  viewers: [RoleId("everyone")],
                  orphaned: undefined,
                  noindex: false,
                  featureFlags: [],
                  collapsed: false,
                  pointsTo: undefined,
                  children: [
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("6"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                    {
                      type: "page",
                      title: "Should be hidden",
                      slug: Slug("hidden"),
                      pageId: PageId("1.mdx"),
                      canonicalSlug: undefined,
                      authed: undefined,
                      id: NodeId("7"),
                      hidden: undefined,
                      icon: undefined,
                      viewers: [RoleId("everyone")],
                      orphaned: undefined,
                      noindex: false,
                      featureFlags: [],
                    },
                  ],
                },
              ],
              title: "Public",
              slug: Slug("public"),
              canonicalSlug: undefined,
              authed: undefined,
              hidden: true,
              icon: undefined,
              viewers: [RoleId("private")],
              orphaned: undefined,
              noindex: false,
              collapsed: false,
              overviewPageId: PageId("1.mdx"),
              pointsTo: undefined,
              featureFlags: [],
            },
          ],
        },
      },
      version: "v2",
      title: "Root",
      slug: Slug("root"),
      canonicalSlug: undefined,
      authed: undefined,
      icon: undefined,
      hidden: false,
      id: NodeId("4"),
      viewers: undefined,
      orphaned: undefined,
      pointsTo: undefined,
      roles: [],
      featureFlags: [],
    });
  });
});
