export { FernRegistry as FdrAPI } from "./generated";
export * as APIV1Db from "./generated/api/resources/api/resources/v1/resources/db";
export * as APIV1Read from "./generated/api/resources/api/resources/v1/resources/read";
export { ReadService as APIV1ReadService } from "./generated/api/resources/api/resources/v1/resources/read/service/ReadService";
export * as APIV1Write from "./generated/api/resources/api/resources/v1/resources/register";
export { RegisterService as APIV1WriteService } from "./generated/api/resources/api/resources/v1/resources/register/service/RegisterService";
export * as DocsV1Db from "./generated/api/resources/docs/resources/v1/resources/db";
export * as DocsV1Read from "./generated/api/resources/docs/resources/v1/resources/read";
export { ReadService as DocsV1ReadService } from "./generated/api/resources/docs/resources/v1/resources/read/service/ReadService";
export * as DocsV1Write from "./generated/api/resources/docs/resources/v1/resources/write";
export { WriteService as DocsV1WriteService } from "./generated/api/resources/docs/resources/v1/resources/write/service/WriteService";
export * as DocsV2Read from "./generated/api/resources/docs/resources/v2/resources/read";
export { ReadService as DocsV2ReadService } from "./generated/api/resources/docs/resources/v2/resources/read/service/ReadService";
export * as DocsV2Write from "./generated/api/resources/docs/resources/v2/resources/write";
export { WriteService as DocsV2WriteService } from "./generated/api/resources/docs/resources/v2/resources/write/service/WriteService";
export { SnippetsFactoryService } from "./generated/api/resources/snippetsFactory/service/SnippetsFactoryService";
export { TemplateService } from "./generated/api/resources/template/service/TemplateService";
export { RootService as SnippetsService } from "./generated/api/service/RootService";
export { register } from "./generated/register";
