// Generated by Wrangler by running `wrangler types`

interface Env {
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	OPENAI_API_KEY: string;
	TURBOPUFFER_API_KEY: string;
	EDGE_CONFIG: string;
	POSTHOG_API_KEY: string;
}
