export { SEARCH_INDEX } from "@fern-ui/fern-docs-search-server/algolia";
export * from "./components/desktop";
export * from "./components/mobile";
export * from "./components/search-client";
export * from "./components/shared";
export { useCmdkShortcut } from "./hooks/use-cmdk-shortcut";
export { useIsMobile } from "./hooks/use-mobile";
export { useSuggestions } from "./hooks/use-suggestions";
export { SuggestionsSchema } from "./server/suggestions-schema";
export { createDefaultSystemPrompt } from "./server/system-prompt";
export * from "./types";
export * from "./utils/facet-display";
