export { visitObject, type ObjectPropertiesVisitor } from "./ObjectPropertiesVisitor.js";
export { addPrefixToString } from "./addPrefixToString.js";
export { assertNever, assertNeverNoThrow } from "./assertNever.js";
export { assertVoidNoThrow } from "./assertVoidNoThrow.js";
export { delay } from "./delay/delay.js";
export { withMinimumTime } from "./delay/withMinimumTime.js";
export { EMPTY_ARRAY, EMPTY_OBJECT } from "./empty.js";
export { identity } from "./identity.js";
export { assertNonNullish, isNonNullish } from "./isNonNullish.js";
export { noop } from "./noop.js";
export { entries, type Entries } from "./objects/entries.js";
export { isPlainObject } from "./objects/isPlainObject.js";
export { keys } from "./objects/keys.js";
export { values, type Values } from "./objects/values.js";
export { PLATFORM, type Platform } from "./platform.js";
export { titleCase } from "./titleCase.js";
export type { Digit, Letter, LowercaseLetter, UppercaseLetter } from "./types.js";
export { visitDiscriminatedUnion } from "./visitDiscriminatedUnion.js";
