export { SEARCH_INDEX } from "@fern-docs/search-server/algolia";
export * from "./components/desktop";
export * from "./components/mobile";
export * from "./components/search-client";
export * from "./components/shared";
export * from "./hooks/use-mobile";
export * from "./server/suggestions-schema";
export { createDefaultSystemPrompt } from "./server/system-prompt";
export * from "./types";
export * from "./utils/facet-display";
