name: E2E @fern-ui/docs-bundle
description: Run Playwright tests on the @fern-ui/docs-bundle package

inputs:
  deployment_url:
    description: "The URL of the deployment to test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      shell: bash
      env:
        DEPLOYMENT_URL: ${{ inputs.deployment_url }}
      run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json pnpm exec playwright test playwright/smoke --workers 6 --reporter json

    - uses: daun/playwright-report-summary@v3
      if: always()
      with:
        report-file: results.json
