name: Deploy @fern-ui/local-preview-bundle (Dry Run)

on:
  pull_request:
    paths:
      - "packages/cdk/**"

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"
  FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}

jobs:
  dev:
    runs-on: ubuntu-latest
    container:
      image: cimg/node:18.18.2
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install
        uses: ./.github/actions/install
      - name: Build local preview bundle
        run: pnpm turbo --filter=@fern-ui/local-preview-bundle build
      - name: Synthesize local preview bundle
        run: pnpm --filter=@fern-ui/cdk run synth:dev2

  prod:
    runs-on: ubuntu-latest
    container:
      image: cimg/node:18.18.2
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install
        uses: ./.github/actions/install
      - name: Build local preview bundle
        run: pnpm turbo --filter=@fern-ui/local-preview-bundle build
      - name: Synthesize local preview bundle
        run: pnpm --filter=@fern-ui/cdk run synth:prod
