name: Preview @fern-ui/docs-bundle
env:
  VERCEL_ORG_ID: team_6FKOM5nw037hv8g2mTk3gaH7
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Preview - app.buildwithfern.com
      url: ${{ steps.deploy.outputs.deployment_url }}
    outputs:
      deployment_url: ${{ steps.deploy.outputs.deployment_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref || github.ref_name || github.ref }}

      - name: Build & Deploy to Vercel
        uses: ./.github/actions/vercel
        id: deploy
        env:
          VERCEL_PROJECT_ID: prj_QX3venU6jwRUmdt8ArfL8AU5r1d4
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          package: "@fern-ui/docs-bundle"
          environment: preview

      - name: Fetch domains
        run: node ./scripts/fetch-domains.js

      - name: Upload domains.txt for playwright tests
        uses: actions/upload-artifact@v3
        with:
          name: domains
          path: domains.txt

  deploy-dev:
    needs: deploy # this will run after the deploy job to leverage turbo's build cache
    runs-on: ubuntu-latest
    environment:
      name: Preview - app-dev.buildwithfern.com
      url: ${{ steps.deploy.outputs.deployment_url }}
    outputs:
      deployment_url: ${{ steps.deploy.outputs.deployment_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build & Deploy to Vercel
        uses: ./.github/actions/vercel
        id: deploy
        env:
          VERCEL_PROJECT_ID: prj_QnsiTm1ijJP6cS23K5da6lL02wbp
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          package: "@fern-ui/docs-bundle"
          environment: preview

      - name: Fetch domains
        run: node ./scripts/fetch-domains.js

      - name: Upload domains.txt for playwright tests
        uses: actions/upload-artifact@v3
        with:
          name: domains
          path: domains.txt

  ete:
    needs: deploy
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # this script generates domains.txt and preview.txt
      - name: Generate preview URLs
        env:
          DEPLOYMENT_URL: ${{ needs.deploy.outputs.deployment_url }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PR_PREVIEW: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Deployment URL: $DEPLOYMENT_URL"
          node scripts/fetch-domains.js

      - name: Comment PR Preview
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          filePath: preview.txt
          comment_tag: pr_preview

      - name: Run E2E tests
        uses: ./.github/actions/ete-docs-bundle
        with:
          deployment_url: ${{ needs.deploy.outputs.deployment_url }}
