name: Deploy FernBot Prod

on:
  push:
    tags: ["*"]

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  GITHUB_APP_ID: ${{ secrets.FERN_BOT_PROD_GITHUB_APP_ID }}
  GITHUB_APP_PRIVATE_KEY: ${{ secrets.FERN_BOT_PROD_GITHUB_APP_PRIVATE_KEY }}
  GITHUB_APP_CLIENT_ID: ${{ secrets.FERN_BOT_PROD_GITHUB_APP_CLIENT_ID }}
  GITHUB_APP_CLIENT_SECRET: ${{ secrets.FERN_BOT_PROD_GITHUB_APP_CLIENT_SECRET }}
  GITHUB_APP_WEBHOOK_SECRET: ${{ secrets.FERN_BOT_PROD_GITHUB_APP_WEBHOOK_SECRET }}
  CO_API_KEY: ${{ secrets.PROD_CO_API_KEY }}

jobs:
  deploy_prod:
    if: github.ref_type == 'tag' && github.event_name == 'push'  && startsWith(github.ref, 'refs/tags/fern-bot@')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 📥 Install
        uses: ./.github/actions/install
      - name: 🚀 serverless deploy
        run: |
          pnpm --filter "@fern-platform/fern-bot" install
          pnpm --filter "@fern-platform/fern-bot" release --stage production
