name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: prj_QX3venU6jwRUmdt8ArfL8AU5r1d4
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"

on:
  deployment_status:

jobs:
  pr-preview:
    # Expected format: Preview - app.buildwithfern.com
    # This deployment should be triggered by Vercel on both PR branches as well as the main branch, where the main branch is the staging environment
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && startsWith(github.event.deployment_status.environment, 'Preview') && endsWith(github.event.deployment_status.environment, 'app.buildwithfern.com')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # this script generates domains.txt and preview.txt
      - name: Generate preview URLs
        env:
          DEPLOYMENT_URL: ${{ github.event.deployment_status.environment_url }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Deployment URL: $DEPLOYMENT_URL"
          node scripts/fetch-domains.js

      - name: Get PR number
        id: pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCHES=$(gh pr list --repo "${{ github.repository }}" --search "${{ github.sha }}" --json headRefName --jq '.[].headRefName')
          MAIN_BRANCH=$(echo $BRANCHES | grep -o 'main' || true)
          echo "::set-output name=branch::$MAIN_BRANCH"

          PR_NUMBER=$(gh pr list --repo "${{ github.repository }}" --search "${{ github.sha }}" --json number --jq '.[0].number')
          echo "::set-output name=pr_number::$PR_NUMBER"

      # skip if branch is main
      - name: Comment PR Preview
        uses: thollander/actions-comment-pull-request@v2
        if: steps.pr.outputs.branch != 'main'
        with:
          filePath: preview.txt
          comment_tag: pr_preview
          pr_number: ${{ steps.pr.outputs.pr_number }}

      - name: Upload domains.txt for playwright tests
        uses: actions/upload-artifact@v3
        with:
          name: domains
          path: domains.txt

  playwright-tests:
    needs: pr-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: domains
          path: .

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        env:
          DEPLOYMENT_URL: ${{ github.event.deployment_status.environment_url }}
        run: pnpm exec playwright test playwright/smoke --workers 6

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
