name: Test FDR ETE

on:
  push:
    branches:
      - main
    paths:
      - "fern/apis/fdr/**"
      - "fern/fern.config.json"
      - "servers/fdr-deploy/**"
      - "servers/fdr/**"
      - ".github/workflows/deploy-fdr.yml"
      - "packages/fdr-sdk/**"
      - "packages/commons/github/**"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - "fern/apis/fdr/**"
      - "fern/fern.config.json"
      - "servers/fdr-deploy/**"
      - "servers/fdr/**"
      - ".github/workflows/deploy-fdr.yml"
      - "packages/fdr-sdk/**"
      - "packages/commons/github/**"
      - "pnpm-lock.yaml"

env:
  PACKAGE_NAME: "@fern-platform/fdr"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"
  FERN_TOKEN: ${{ secrets.FERN_TOKEN }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # This helps turbo resolve changes faster

      - name: Install
        uses: ./.github/actions/install

      - name: Run ete test
        run: pnpm --filter=@fern-platform/fdr test:ete
