# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: "Next.js Bundle Analysis"
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: prj_QX3venU6jwRUmdt8ArfL8AU5r1d4
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

on:
  pull_request:
  push:
    branches:
      - main # change this if your default branch is named differently
  workflow_dispatch:

defaults:
  run:
    # change this if your nextjs app does not live at the root of the repo
    working-directory: ./

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install
        with:
          install: false

      - name: Build Docs Bundle with Analyze
        env:
          ANALYZE: 1
        run: |
          pnpm install --global vercel@latest
          vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Analyze bundle
        run: pnpm --package=nextjs-bundle-analysis dlx report

      - name: Upload analysis
        uses: actions/upload-artifact@v4
        with:
          name: analyze
          path: packages/ui/docs-bundle/.next/analyze/

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: nextjs_bundle_analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: packages/ui/docs-bundle/.next/analyze/base

      # https://infrequently.org/2021/03/the-performance-inequality-gap/
      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR packages/ui/docs-bundle/.next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: Comment PR Preview
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: packages/ui/docs-bundle/.next/analyze/__bundle_analysis_comment.txt
          comment_tag: bundle_analysis
