name: Publish Parsers Package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/parsers/package.json'

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check package.json changes
        id: check-version
        run: |
          CHANGED=$(git diff HEAD^ HEAD -- packages/parsers/package.json | grep '"version":' || true)
          if [ ! -z "$CHANGED" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.check-version.outputs.version_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        if: steps.check-version.outputs.version_changed == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        if: steps.check-version.outputs.version_changed == 'true'
        run: pnpm install

      - name: Compile package
        if: steps.check-version.outputs.version_changed == 'true'
        run: cd packages/parsers && pnpm compile

      - name: Publish to npm
        if: steps.check-version.outputs.version_changed == 'true'
        run: cd packages/parsers && pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
