name: Publish FDR SDK

on:
  workflow_call:

jobs:
  publish_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: 🧪 Build and test
        run: pnpm turbo codegen build test --filter=${{ env.PACKAGE_NAME }}

      - name: Publish FDR SDK
        run: |
          git_version="$(scripts/fdr-version.sh)"
          cd packages/fdr-sdk
          mv package.json package.json.tmp
          version_replace="s/0.0.0/${git_version}/"
          cat package.json.tmp| sed "${version_replace}" > package.json
          rm -rf package.json.tmp
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public
