name: "Publish Read SDKs"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install fern
        run: npm install -g fern-api
      - name: Publish FDR SDKs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: | 
          git_version="$(scripts/git-version.sh)"
          fern generate --group internal-read --version "${git_version}" --log-level debug
