name: Publish Postman

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: main

jobs:
  publish_fdr_postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish Fiddle FDR SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          fern generate --api fdr --group postman
