name: Publish FDR SDKs

on:
  workflow_call:
  workflow_dispatch:

env:
  PACKAGE_NAME: "@fern-platform/fdr"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"
  FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}

jobs:
  publish_fiddle_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || "main" }}

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish Fiddle FDR SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          git_version="$(scripts/fdr-version.sh)"
          fern generate --api fdr --group fiddle --version $git_version

  publish_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || "main" }}

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: 🧪 Build and test
        run: pnpm turbo codegen build test --filter=${{ env.PACKAGE_NAME }}

      - name: Publish FDR SDK
        env:
          NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
        run: |
          git_version="$(scripts/fdr-version.sh)"
          cd packages/fdr-sdk
          mv package.json package.json.tmp
          version_replace="s/0.0.0/${git_version}/"
          cat package.json.tmp| sed "${version_replace}" > package.json
          rm -rf package.json.tmp
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public
