name: Publish FDR SDKs

on:
  workflow_call:
  workflow_dispatch:

env:
  PACKAGE_NAME: "@fern-platform/fdr"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"
  FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}

jobs:
  publish_fiddle_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish Fiddle FDR SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          git_version="$(scripts/fdr-version.sh)"
          fern generate --api fdr --group fiddle --version $git_version

  publish_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: 🧪 Build and test
        run: pnpm turbo codegen build test --filter=${{ env.PACKAGE_NAME }}

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish FDR SDK
        env:
          NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
        run: |
          git_version="$(scripts/fdr-version.sh)"
          working_dir=$(pwd)
          cd packages/commons/core-utils
          mv package.json package.json.tmp
          version_replace="s/0.0.0/${git_version}/"
          cat package.json.tmp| sed "${version_replace}" > package.json
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          rm -rf package.json.tmp
          npm publish --access public
          cd $working_dir/packages/fdr-sdk
          mv package.json package.json.tmp
          workspace_replace="s/workspace:*/${git_version}/"
          cat package.json.tmp| sed "${version_replace}" > package.json.workspace
          cat package.json.workspace | sed "${workspace_replace}" > package.json
          rm -rf package.json.tmp package.json.workspace
          npm publish --access public

      - name: Publish CJS SDK
        env:
          NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
        run: |
          git_version="$(scripts/fdr-version.sh)"
          fern generate --api fdr --group fdr-cjs-sdk --version ${git_version} --log-level debug
          fern generate --api fdr --group generators-sdk --version ${git_version} --log-level debug
          fern generate --api fdr --group paged-generators-sdk --version ${git_version} --log-level debug
