name: Testing
on: pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Testing
        run: |
          DEPLOYMENT_INFO=$(curl -s -X GET "https://api.vercel.com/v13/deployments/app.buildwithfern.com?teamId=team_6FKOM5nw037hv8g2mTk3gaH7&withGitRepoInfo=false" -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}")
          echo "DEPLOYMENT INFO:"
          echo $DEPLOYMENT_INFO

          echo "---------------------------------"
          echo "ALIASES:"
          ALIASES=$(jq -r '.alias[]' <<< $DEPLOYMENT_INFO)
          echo $ALIASES

          for DOMAIN in ${ALIASES[@]}; do
            if [[ "$DOMAIN" != *"buildwithfern.com"* ]] && [[ "$DOMAIN" != *"vercel.app"* ]]; then
              echo "- [ ] [$DOMAIN](https://$DEPLOYMENT_URL/api/fern-docs/preview?host=$DOMAIN)"
            fi
          done
